[global]
frame_color = "#f0be6d"
highlight = "#f0be6d"
separator_color= "#9b8f80"

[experimental]
per_monitor_dpi = false

[urgency_low]
background = "#17130b"
foreground = "#ece1d4"
highlight = "#604100"

[urgency_normal]
background = "#17130b"
foreground = "#ece1d4"
highlight = "#604100"

[urgency_critical]
background = "#17130b"
foreground = "#ece1d4"
highlight = "#ffb4ab"
