[config]
caching = true

# TODO: GTK3 - https://github.com/InioX/matugen-themes?tab=readme-ov-file#gtk
# TODO: launcher - (rofi, etc)
# TODO: notifications - (mako, dunst, etc)
# TODO: qt
# TODO: starship

[templates.btop]
input_path = 'templates/btop.theme'
output_path = 'output/btop.theme'

[templates.dunst]
input_path = 'templates/dunst-theme.conf'
output_path = 'output/dunst-theme.conf'

[templates.hyprland]
input_path = 'templates/hyprland-colors.conf'
output_path = 'output/hyprland-colors.conf'

[templates.hyprlock]
input_path = 'templates/hyprlock-colors.conf'
output_path = 'output/hyprlock-colors.conf'

[templates.kitty]
# TODO:: still needs work - https://github.com/InioX/matugen-themes?tab=readme-ov-file#kitty
input_path = 'templates/kitty-colors.conf'
output_path = 'output/kitty-colors.conf'

[templates.pywal]
input_path = 'templates/pywal.json'
output_path = 'output/pywal.json'

[templates.rofi]
input_path = 'templates/rofi-colors.rasi'
output_path = 'output/rofi-colors.rasi'

[templates.walker]
input_path = 'templates/walker-colors.css'
output_path = 'output/walker-colors.css'

[templates.waybar]
input_path = 'templates/waybar-colors.css'
output_path = 'output/waybar-colors.css'

[templates.yazi]
input_path = 'templates/yazi-theme.toml'
output_path = 'output/yazi-theme.toml'
