# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
  disable_hyprland_logo = true
  disable_splash_rendering  = true
  focus_on_activate = true
}

xwayland {
  force_zero_scaling = true
}

# Don't show update on first launch
ecosystem {
  no_update_news = true
}
