env = DOTFILES_DIR,$dotfiles
env = WALLPAPER_DIR,$wallpapers
env = CODE_DIR,$code_dir
env = HYPR_SCRIPTS_DIR,$scripts_dir

source = ~/.config/hypr/colors.conf

# autostart

## background processes
exec-once = uwsm-app -s s -- hyprdynamicmonitors run
exec-once = uwsm-app -s s -- gnome-keyring-daemon --start --components=pkcs11,secrets,ssh
exec-once = uwsm-app -s s -- /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = uwsm-app -s s -- wl-clip-persist --clipboard regular --all-mime-type-regex '^(?!x-kde-passwordManagerHint).+'
exec-once = uwsm-app -s s -- playerctld daemon

## desktop components
exec-once = uwsm-app -s s -- hyprpaper --config $dotfiles/hypr/hyprpaper.conf
exec-once = uwsm-app -s s -- hypridle
exec-once = uwsm-app -s s -- swaync
exec-once = $dotfiles/hypr/scripts/generate-hyprsunset-config.sh && uwsm-app -s s -- hyprsunset
exec-once = uwsm-app -s s -- waybar

exec-once = uwsm-app -s s -- tailscale systray
exec-once = uwsm-app -s s -- $dotfiles/hypr/scripts/hypr-event-listener.sh
exec-once = uwsm-app -s s -- $dotfiles/hypr/scripts/system-update-check-interval.sh

exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd --all

# app rules
source = apps/*

# bindings
source = bindings/*

# style
source = style/*

# display
monitor = , preferred, auto, 1

# render - https://wiki.hypr.land/Configuring/Variables/#render
render {
  direct_scanout = 1
}

# input - http://wiki.hyprland.org/Configuring/Variables/#input-1
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
  kb_layout = us
  kb_options = compose:caps # ,grp:alts_toggle

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Start with numlock on by default
  numlock_by_default = true

  # Move focus to monitor under mouse when moving mouse between monitors
  follow_mouse = 1

  # Increase sensitity for mouse/trackpack (default: 0)
  # sensitivity = 0.35

  # Mouse acceleration (adaptive, flat, custom) (default:[empty])
  accel_profile = flat

  # http://wiki.hyprland.org/Configuring/Variables/#touchpad
  touchpad {
    # Use natural (inverse) scrolling
    # natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4
  }
}

# Enable touchpad gestures for changing workspaces
# See https://wiki.hyprland.org/Configuring/Gestures/
gesture = 3, horizontal, workspace

# env
# Cursor size
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Force all apps to use Wayland
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_STYLE_OVERRIDE,kvantum
env = SDL_VIDEODRIVER,wayland,x11
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = OZONE_PLATFORM,wayland
env = XDG_SESSION_TYPE,wayland

# Allow better support for screen sharing (Google Meet, Discord, etc)
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland

# Use XCompose file
env = XCOMPOSEFILE,~/.XCompose

# Keyring
env = SSH_AUTH_SOCK,$XDG_RUNTIME_DIR/gnupg/S.gpg-agent.ssh
