general {
    lock_cmd = pidof hyprlock || hyprlock --config $DOTFILES_DIR/hypr/hyprlock.conf      # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

# 15min - screen off
listener {
  timeout = 900
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}

# 30min - lock
listener {
  timeout = 1800
  on-timeout = loginctl lock-session
}
