# cool to default (6000) starting at 7:00 and ending at 8:00
profile {
  time = 7:00
  temperature = 3500
}

profile {
  time = 7:12
  temperature = 4000
}

profile {
  time = 7:24
  temperature = 4500
}

profile {
  time = 7:36
  temperature = 5000
}

profile {
  time = 7:48
  temperature = 5500
}

profile {
  time = 8:00
  identity = true
}

# warm to 3000 starting at 15:00 and ending at 16:00
profile {
  time = 15:00
  temperature = 5500
}

profile {
  time = 15:12
  temperature = 5000
}

profile {
  time = 15:24
  temperature = 4500
}

profile {
  time = 15:36
  temperature = 4000
}

profile {
  time = 15:48
  temperature = 3500
}

profile {
  time = 16:00
  temperature = 3000
}
