[global]
frame_color = "{color1}"
highlight = "{color1}"
separator_color= "{color8}"

[experimental]
per_monitor_dpi = false

[urgency_low]
background = "{background}"
foreground = "{foreground}"
highlight = "{color1}"

[urgency_normal]
background = "{background}"
foreground = "{foreground}"
highlight = "{color1}"

[urgency_critical]
background = "{background}"
foreground = "{foreground}"
highlight = "{color2}"
