source = ~/.config/hypr/colors.conf

# Browser types
windowrule {
  name = browser-chromium
  match:class = chromium|google-chrome

  tile = on
  tag = +browser
}

windowrule {
  name = browser-firefox
  match:class = firefox

  tag = +browser
}

# Browser opacity
windowrule {
  name = browser-opacity
  match:tag = browser

  opacity = 1 0.97
}

windowrule {
  name = browser-call-pip
  match:tag = browser
  match:title = (Meet - .*)
  match:float = 1

  pin = on
  size = 320 180
  keep_aspect_ratio = on
  border_color = $accent_primary $accent_primary
  opacity = 1 1
  move = monitor_w-window_w-10 40
}
