# Browser types
windowrule {
  name = browser-chromium
  match:class = ([cC]hrom(e|ium)|google-chrome|[bB]rave-browser|Microsoft-edge|Vivaldi-stable)

  tile = on
  tag = +browser
}

windowrule {
  name = browser-firefox
  match:class = ([fF]irefox|zen|librewolf)

  tag = +browser
}

# Browser opacity
windowrule {
  name = browser-opacity
  match:tag = browser

  opacity = 1 0.97
}

windowrule {
  name = browser-opacity-exceptions
  match:tag = browser
  match:title = (- YouTube)

  opacity = 1 1.0
}
