# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule {
  name = window-defaults
  match:class = .*

  suppressevent = maximize
  opacity = 0.97 0.9
}

windowrule {
  name = xwayland-dragging-fix
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:floating = 1
  match:fullscreen = 0
  match:pinned = 0

  nofocus = on
}
