# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule {
  name = window-defaults
  match:class = .*

  suppress_event = maximize
  opacity = 0.97 0.9
}

windowrule {
  name = xwayland-dragging-fix
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0

  no_focus = on
}
