# Steam
windowrule {
  name = steam-main-window
  match:class = steam

  opacity = 1 1
  idle_inhibit = fullscreen
}

windowrule {
  name = steam-friends-list
  match:class = steam
  match:title = Friends List

  float = on
  size = 400 600
}

windowrule {
  name = steam-games
  match:class = (steam_app_\d+)

  content = game
  tag = +game
}

# RetroArch
windowrule {
  name = retroarch
  match:class = retroarch

  content = game
  tag = +game
}

# Games
windowrule {
  name = games
  match:tag = game

  opacity = 1 1
  fullscreen = on
  idle_inhibit = fullscreen
}

