# Steam
windowrule {
  name = steam-main-window
  match:class = steam
  match:title = ^Steam$

  opacity = 1 1
  idle_inhibit = fullscreen
}

windowrule {
  name = steam-signin-window
  match:class = steam
  match:title = ^Sign in to Steam$

  float = on
  center = on
}

windowrule {
  name = steam-other-windows
  match:class = steam
  match:title = negative:^Steam$

  float = on
  opacity = 1 1
}

# Games
windowrule {
  name = steam-games
  match:class = (steam_app_\d+|gamescope|retroarch|net.retrodeck.retrodeck)

  content = game
  opaque = on
  fullscreen = on
  immediate = on
  idle_inhibit = fullscreen
  no_anim = on
  no_blur = on
}
