# Nextcloud - fixing popup disappearing too early
windowrule {
  name = nextcloud
  match:class = com.nextcloud.desktopclient.nextcloud

  float = on
  move = monitor_w-window_w-10 55
  no_initial_focus = on
}
