# fixing popup disappearing too early
windowrulev2 = float, class:com.nextcloud.desktopclient.nextcloud
windowrulev2 = move onscreen 100%-w-10 55, class:com.nextcloud.desktopclient.nextcloud
windowrulev2 = noinitialfocus, class:com.nextcloud.desktopclient.nextcloud
