source = ~/.config/hypr/colors.conf

# Browser PiP video
windowrule {
  name = pip-browser
  match:title = (Picture.?in.?[Pp]icture)

  tag = +pip
}

# Spotify mini player
windowrule {
  name = pip-spotify
  match:class = ([Cc]hromium-browser)
  match:title = (.* • .*)
  match:float = 1

  tag = +pip
}

# Picture-in-Picture windows
windowrule {
  name = pip-windows
  match:tag = pip

  float = on
  pin = on
  size = 600 338
  keep_aspect_ratio = on
  border_color = $color1 $color1
  opacity = 1 1
  move = monitor_w-window_w-10 55
}
