source = ~/.config/hypr/colors.conf

# Browser PiP video
windowrule {
  name = pip-browser
  match:title = (Picture.?in.?[Pp]icture)

  tag = +pip
  suppress_event = activate activatefocus
}

# Spotify mini player
windowrule {
  name = pip-spotify
  match:class = ([Cc]hromium-browser)
  match:title = (.* • .*)
  match:float = 1

  tag = +pip
  suppress_event = activate activatefocus
}

# Picture-in-Picture windows
windowrule {
  name = pip-windows
  match:tag = pip

  float = on
  pin = on
  size = 600 338
  keep_aspect_ratio = on
  border_color = $accent_primary $accent_primary
  opacity = 1 1
  move = monitor_w-window_w-10 40
}
