source = ~/.cache/wal/colors-hyprland-extra.conf

# Slack Huddle popout windows
windowrulev2 = float, class:(Slack), initialTitle:(Huddle)
windowrulev2 = pin, class:(Slack), initialTitle:(Huddle)
windowrulev2 = size 400 250, class:(Slack), initialTitle:(Huddle)
windowrulev2 = move onscreen 100%-w-10 55, class:(Slack), initialTitle:(Huddle)

windowrulev2 = bordercolor $color2hex $color2hex, class:(Slack), initialTitle:(Huddle)
windowrulev2 = opacity 1 1, class:(Slack), initialTitle:(Huddle)
