source = ~/.config/hypr/colors.conf

# Slack Huddle popout windows
windowrule {
  name = slack-huddle
  match:class = (Slack)
  match:title = ^(Huddle)

  float = on
  pin = on
  size = 400 250
  move = monitor_w-window_w-10 40
  border_color = $color2 $color2
  opacity = 1 1
}
