source = ~/.cache/wal/colors-hyprland-extra.conf

# Slack Huddle popout windows
windowrule {
  name = slack-huddle
  match:class = (Slack)
  match:title = ^(Huddle)

  float = on
  pin = on
  size = 400 250
  move = (monitor_w - window_w - 10) 55
  bordercolor = $color2hex $color2hex
  opacity = 1 1
}
