# Steam
#windowrulev2 = float, class:steam
#windowrulev2 = center, class:steam, title:Steam
windowrulev2 = opacity 1 1, class:steam
#windowrulev2 = size 1100 700, class:steam, title:Steam
windowrulev2 = float, size 400 600, class:steam, title:Friends List
windowrulev2 = idleinhibit fullscreen, class:steam

# Games
windowrulev2 = content game, class:(steam_app_\d+)

windowrulev2 = fullscreen, content:game
windowrulev2 = idleinhibit fullscreen, content:game
