# Steam
#windowrule = float, class:steam
#windowrule = center, class:steam, title:Steam
windowrule = opacity 1 1, class:steam
#windowrule = size 1100 700, class:steam, title:Steam
windowrule = float, size 400 600, class:steam, title:Friends List
windowrule = idleinhibit fullscreen, class:steam

# Games
windowrule = content game, class:(steam_app_.*)

windowrule = fullscreen, idleinhibit fullscreen, content:game
