# Define terminal tag to style them uniformly
windowrulev2 = tag +terminal, class:(Alacritty|kitty|com.mitchellh.ghostty)

# Scroll faster in the terminal
windowrulev2 = scrolltouchpad 1.5, tag:terminal
