# Waybar popups
windowrule {
  name = waybar-popup
  match:class = waybar.float

  float = on
  move = (monitor_w - window_w - 10) 55
  size = 500 800
  dimaround = on
  pin = on
  stayfocused = on
}
