windowrulev2 = tag +waybar-popup, class:(waybar.float)

windowrulev2 = float, tag:waybar-popup
windowrulev2 = move onscreen 100%-w-10 55, tag:waybar-popup
windowrulev2 = size 500 800, tag:waybar-popup
windowrulev2 = dimaround on, tag:waybar-popup
windowrulev2 = pin, tag:waybar-popup
windowrulev2 = stayfocused, tag:waybar-popup
