# 1 - terminal
# 2 - browser
# 3 - editors
# 4 - notes
# 5 - communication
# 6 - media
# 7 - games

workspace = 1, persistent:true
workspace = 2, persistent:true
workspace = 3, persistent:true
workspace = 4, persistent:true
workspace = 5, persistent:true
workspace = 6, persistent:true
workspace = 7, persistent:true

# 1. Terminal
windowrule {
  name = workspace-terminal
  match:class = (kitty)

  workspace = 1
}

# 2. Browsers
windowrule {
  name = workspace-browser
  match:class = (firefox|google-chrome)

  workspace = 2
}

# 3. Editors
windowrule {
  name = workspace-editors
  match:class = (code|cursor|chrome-chatgpt.com_.*)

  workspace = 3
}

# 4. Notes
windowrule {
  name = workspace-notes
  match:class = (obsidian)

  workspace = 4
}

# 5. Messaging
windowrule {
  name = workspace-messaging
  match:class = (discord|Slack|signal)

  workspace = 5
}

windowrule {
  name = workspace-messaging-zoom
  match:class = (zoom)
  match:title = (Meeting|Zoom Workplace)

  workspace = 5
}

# 6. Media
windowrule {
  name = workspace-media
  match:class = (Spotify|mpv|io.github.celluloid_player.Celluloid)

  workspace = 6
}

# 7. Games
windowrule {
  name = workspace-games
  match:class = (steam|steam_app_.*|gamescope|retroarch|net.retrodeck.retrodeck)

  workspace = 7
}
