# Fix disappearing pop-ups in zoom
windowrulev2 = suppressevent activatefocus, class:zoom, title:!(menu window|confirm window)
windowrulev2 = stayfocused, class:zoom, title:(menu window)
windowrulev2 = stayfocused, class:zoom, title:(confirm window)

# meeting reminders
windowrulev2 = move onscreen 100%-w-10 55, class:zoom, title:zoom_linux_float_message_reminder # TODO: validate position
windowrulev2 = pin, class:zoom, title:zoom_linux_float_message_reminder
windowrulev2 = noborder, class:zoom, title:zoom_linux_float_message_reminder
windowrulev2 = noanim, class:zoom, title:zoom_linux_float_message_reminder
windowrulev2 = noblur, class:zoom, title:zoom_linux_float_message_reminder

# other pop ups
windowrulev2 = noborder, class:zoom, title:(Zoom Workplace), floating:1
