# Fix disappearing pop-ups in zoom
windowrule {
  name = zoom-suppress-focus
  match:class = zoom
  match:title = negative:(menu window|confirm window|zoom)

  suppress_event = activatefocus
}

windowrule {
  name = zoom-popups
  match:class = zoom
  match:title = (menu window|confirm window)

  stay_focused = on
}

# meeting reminders
windowrule {
  name = zoom-reminders
  match:class = zoom
  match:title = zoom_linux_float_message_reminder|zoom

  move = monitor_w-window_w-10 55
  pin = on
  border_size = 0
  no_anim = on
  no_blur = on
}

# other pop ups
windowrule {
  name = zoom-after-meeting-popups
  match:class = zoom
  match:title = ^Zoom Workplace$

  float = on
}
