# Fix disappearing pop-ups in zoom
windowrulev2 = stayfocused, title:^(menu window)$, class:^(zoom)$
windowrulev2 = stayfocused, title:^(confirm window)$, class:^(zoom)$

# meeting reminders
windowrulev2 = move onscreen 100%-w-10 55, title:zoom_linux_float_message_reminder # TODO: validate position
windowrulev2 = pin, title:zoom_linux_float_message_reminder

# other pop ups
windowrulev2 = noborder, title:(Zoom Workplace), class:zoom, floating:1
