bindd = SUPER, return, Terminal, exec, uwsm-app -- kitty --working-directory="$($dotfiles/hypr/scripts/terminal-cwd.sh)"
bindd = SUPER, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER, B, Browser, exec, uwsm-app -- firefox
bindd = SUPER SHIFT, B, Browser (private), exec, uwsm-app -- firefox --private-window
