# Menus
bindd = SUPER, SPACE, Launch apps, exec, rofi -config $dotfiles/rofi/config.rasi -show drun

# Notifications
bindd = SUPER, COMMA, Dismiss last notification, exec, makoctl dismiss
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, makoctl dismiss --all
bindd = SUPER CTRL, COMMA, Toggle silencing notifications, exec, makoctl mode -t do-not-disturb && makoctl mode | grep -q 'do-not-disturb' && notify-send "Silenced notifications" || notify-send "Enabled notifications"

# Lock screen
bindd = SUPER, L, Lock screen, exec, hyprlock

# Toggle idling
# bindd = SUPER CTRL, I, Toggle locking on idle, exec, omarchy-toggle-idle

# Toggle nightlight
# bindd = SUPER CTRL, N, Toggle nightlight, exec, omarchy-toggle-nightlight

# Screenshots
# bindd = , PRINT, Screenshot of region, exec, omarchy-cmd-screenshot
# bindd = SHIFT, PRINT, Screenshot of window, exec, omarchy-cmd-screenshot window
# bindd = CTRL, PRINT, Screenshot of display, exec, omarchy-cmd-screenshot output

# Screen recordings
# bindd = ALT, PRINT, Screen record a region, exec, omarchy-cmd-screenrecord region
# bindd = ALT SHIFT, PRINT, Screen record a region with audio, exec, omarchy-cmd-screenrecord region audio
# bindd = CTRL ALT, PRINT, Screen record display, exec, omarchy-cmd-screenrecord output
# bindd = CTRL ALT SHIFT, PRINT, Screen record display with audio, exec, omarchy-cmd-screenrecord output audio
