## Notifications
bindd = SUPER, COMMA, Dismiss last notification, exec, makoctl dismiss
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, makoctl dismiss --all
bindd = SUPER CTRL, COMMA, Toggle silencing notifications, exec, makoctl mode -t do-not-disturb && makoctl mode | grep -q 'do-not-disturb' && notify-send "Silenced notifications" || notify-send "Enabled notifications"

## Utility
bindd = SUPER, H, Show help for keybindings, exec, uwsm-app -- kitty --class TUI.float /bin/bash -c "$dotfiles/hypr/scripts/bindings.sh | less"
bindd = SUPER, L, Lock screen, exec, pidof hyprlock || hyprlock --config $dotfiles/hypr/hyprlock.conf
bindd = SUPER CTRL, I, Toggle locking on idle, exec, notify-send "TODO: Toggle locking on idle script"
bindd = SUPER CTRL, N, Toggle nightlight, exec, notify-send "TODO: Toggle nightlight script"

## Screenshots
bindd = , PRINT, Screenshot of region, exec, notify-send "TODO: Screenshot of region script"
bindd = SHIFT, PRINT, Screenshot of window, exec, notify-send "TODO: Screenshot of window script"
bindd = CTRL, PRINT, Screenshot of display, exec, notify-send "TODO: Screenshot of display script"

## Screen recordings
bindd = ALT, PRINT, Screen record a region, exec, notify-send "TODO: Screen record a region script"
bindd = ALT SHIFT, PRINT, Screen record a region with audio, exec, notify-send "TODO: Screen record a region with audio script"
bindd = CTRL ALT, PRINT, Screen record display, exec, notify-send "TODO: Screen record display script"
bindd = CTRL ALT SHIFT, PRINT, Screen record display with audio, exec, notify-send "TODO: Screen record display with audio script"
