## Notifications
bindd = SUPER, COMMA, Dismiss last notification, exec, dunstctl close
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, dunstctl close-all
bindd = SUPER CTRL, COMMA, Toggle silencing notifications, exec, $dotfiles/hypr/scripts/toggle-dnd.sh

## Utility
bindd = SUPER, H, Show help for keybindings, exec, uwsm-app -- kitty --class TUI.float /bin/bash -c "$dotfiles/hypr/scripts/bindings.sh | less"
bindd = SUPER, L, Lock screen, exec, pidof hyprlock || hyprlock --config $dotfiles/hypr/hyprlock.conf
bindd = SUPER CTRL, I, Toggle locking on idle, exec, notify-send "TODO: Toggle locking on idle script"
bindd = SUPER CTRL, N, Toggle nightlight, exec, notify-send "TODO: Toggle nightlight script"

## Screenshots
bindd = SUPER CTRL, S, Screenshot of region, exec, $dotfiles/hypr/scripts/screen-shot.sh region
bindd = SUPER SHIFT, S, Screenshot of window, exec, $dotfiles/hypr/scripts/screen-shot.sh window
bindd = SUPER, S, Screenshot of display, exec, $dotfiles/hypr/scripts/screen-shot.sh output

## Screen recordings
bindd = SUPER CTRL, R, Screen record a region, exec, $dotfiles/hypr/scripts/screen-recording.sh region
bindd = SUPER SHIFT, R, Screen record a window, exec, $dotfiles/hypr/scripts/screen-recording.sh window
bindd = SUPER, R, Screen record display, exec, $dotfiles/hypr/scripts/screen-recording.sh output
