# Laptop Lid Switch
bindl = , switch:lid,     exec, hyprlock
bindl = , switch:on:lid,  exec, hyprctl keyword monitor "eDP-1, preferred, auto, 1"
bindl = , switch:off:lid, exec, hyprctl keyword monitor "eDP-1, disable"
