## Aesthetics
bindd = SUPER, T, Launch Wallpaper and Theme Selector, exec, $dotfiles/hypr/scripts/set-theme.sh
bindd = SUPER, BACKSPACE, Toggle window transparency, exec, hyprctl dispatch setprop "address:$(hyprctl activewindow -j | jq -r '.address')" opaque toggle
